version: '3.8'
services:
  mongodb:
    image: bitnami/mongodb
    container_name: mongodb
    environment:
      MONGODB_ROOT_USER: rootadmin
      MONGODB_ROOT_PASSWORD: rootpassword
      MONGODB_DATABASE: calendarapp
      MONGODB_USERNAME: calendarapp_user
      MONGODB_PASSWORD: userpassword
    ports:
      - "27017:27017"
#    volumes:
#      - ./init:/docker-entrypoint-initdb.d

volumes:
  mongodb-data:
